export const dynamic = 'force-dynamic';
import { NextResponse } from 'next/server';
import { Resend } from 'resend';
import { adminClient } from '@/sanity/lib/client';

const resend = new Resend(process.env.RESEND_API_KEY || 're_dummy_key_for_build');

export async function POST(req: Request) {
  try {
    const teamEmail = process.env.TEAM_EMAIL || 'nexus.civicpluse@gmail.com';

    // Fetch weekly stats from Sanity
    const query = `{
      "totalIssues": count(*[_type == "issue"]),
      "resolvedIssues": count(*[_type == "issue" && status == "Resolved"]),
      "criticalIssues": count(*[_type == "issue" && severity == "high" && status != "Resolved"])
    }`;
    const stats = await adminClient.fetch(query);

    const emailHtml = `
      <div style="font-family: 'Courier New', Courier, monospace; background-color: #020408; color: #f1f5f9; padding: 40px; border: 1px solid #14b8a6; border-radius: 16px; max-width: 600px; margin: 0 auto;">
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #2dd4bf; margin: 0; font-size: 24px; letter-spacing: 2px; text-transform: uppercase;">CivicPulse Nexus</h1>
          <p style="color: #64748b; font-size: 12px; letter-spacing: 4px; margin-top: 5px;">WEEKLY IMPACT DIGEST</p>
        </div>
        
        <div style="background-color: #0f172a; border: 1px solid #1e293b; padding: 20px; border-radius: 12px; margin-bottom: 25px;">
          <h2 style="color: #f8fafc; font-size: 16px; border-bottom: 1px solid #334155; padding-bottom: 10px; margin-top: 0;">System Telemetry Overview</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; color: #94a3b8;">Total Hazards Logged:</td>
              <td style="padding: 8px 0; color: #38bdf8; text-align: right; font-weight: bold;">${stats.totalIssues}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #94a3b8;">Hazards Resolved:</td>
              <td style="padding: 8px 0; color: #10b981; text-align: right; font-weight: bold;">${stats.resolvedIssues}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; color: #94a3b8;">Pending Critical (SLA 4H):</td>
              <td style="padding: 8px 0; color: #ef4444; text-align: right; font-weight: bold;">${stats.criticalIssues}</td>
            </tr>
          </table>
        </div>

        <div style="text-align: center; margin-top: 40px; border-top: 1px solid #1e293b; padding-top: 20px;">
          <p style="color: #64748b; font-size: 10px;">Generated by the Autonomous Command Nexus.</p>
        </div>
      </div>
    `;

    const { data, error } = await resend.emails.send({
      from: 'CivicPulse Nexus <onboarding@resend.dev>',
      to: [teamEmail],
      subject: '📊 CivicPulse Nexus: Weekly Impact Digest',
      html: emailHtml,
    });

    if (error) {
      console.error('Resend error:', error);
      return NextResponse.json({ error }, { status: 400 });
    }

    return NextResponse.json({ success: true, data });

  } catch (error) {
    console.error('Digest Error:', error);
    return NextResponse.json({ error: 'Failed to generate digest' }, { status: 500 });
  }
}
