import { defineField, defineType } from 'sanity';

export const resolution = defineType({
  name: 'resolution',
  title: 'Contractor Resolutions',
  type: 'document',
  fields: [
    defineField({
      name: 'issue',
      title: 'Linked Issue',
      type: 'reference',
      to: [{ type: 'issue' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'contractorEmail',
      title: 'Contractor Email',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'resolutionImage',
      title: 'Resolution Evidence (After Photo)',
      type: 'image',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'forensicReport',
      title: 'AI Forensic Report',
      type: 'text',
      description: 'The raw report generated by the AI comparing before and after photos.',
    }),
    defineField({
      name: 'bills',
      title: 'Material & Labor Bills',
      type: 'array',
      of: [{ type: 'file', options: { accept: 'image/*,application/pdf' } }],
      validation: (Rule) => Rule.min(1).max(10),
    }),
    defineField({
      name: 'videoStart',
      title: 'Video 1: Start of Work',
      type: 'file',
      options: { accept: 'video/*' },
    }),
    defineField({
      name: 'videoProgress',
      title: 'Video 2: Work in Progress',
      type: 'file',
      options: { accept: 'video/*' },
    }),
    defineField({
      name: 'workerLeftNote2',
      title: 'Worker Left Reason (Stage 2 - Progress)',
      type: 'text',
    }),
    defineField({
      name: 'videoContinued',
      title: 'Video 3: Continued Work',
      type: 'file',
      options: { accept: 'video/*' },
    }),
    defineField({
      name: 'workerLeftNote3',
      title: 'Worker Left Reason (Stage 3 - Continued)',
      type: 'text',
    }),
    defineField({
      name: 'videoComplete',
      title: 'Video 4: Completed Work',
      type: 'file',
      options: { accept: 'video/*' },
    }),
    defineField({
      name: 'workerLeftNote4',
      title: 'Worker Left Reason (Stage 4 - Completed)',
      type: 'text',
    }),
    defineField({
      name: 'aiVerificationScore',
      title: 'AI Confidence Score (%)',
      type: 'number',
    }),
    defineField({
      name: 'status',
      title: 'Verification Status',
      type: 'string',
      options: {
        list: [
          { title: 'Pending Admin Review', value: 'Pending' },
          { title: 'Verified', value: 'Verified' },
          { title: 'Rejected', value: 'Rejected' },
        ],
      },
      initialValue: 'Pending',
    }),
    defineField({
      name: 'physicalReviewStatus',
      title: 'Physical Review by Citizen',
      description: 'Select the outcome if a physical citizen review was conducted.',
      type: 'string',
      options: {
        list: [
          'Review Pending',
          'Citizen Verified (Issue Resolved on Site)',
          'Citizen Rejected (Issue Not Resolved)',
          'Admin Overruled Citizen Review'
        ],
      },
    }),
    defineField({
      name: 'year',
      title: 'Year',
      type: 'string',
    }),
    defineField({
      name: 'month',
      title: 'Month',
      type: 'string',
    }),
    defineField({
      name: 'day',
      title: 'Day',
      type: 'string',
    }),
    defineField({
      name: 'dateResolved',
      title: 'Date Submitted',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
    }),
  ],
  preview: {
    select: {
      title: 'contractorEmail',
      status: 'status',
      day: 'day',
      month: 'month',
      year: 'year',
      media: 'resolutionImage'
    },
    prepare(selection) {
      const { title, status, day, month, year, media } = selection;
      return {
        title: `Resolution by: ${title}`,
        subtitle: `${status} - ${day}/${month}/${year}`,
        media,
      };
    },
  },
});
